export const host = "https://pora-vipit-back.herokuapp.com";
// export const host = "http://localhost:5001";
export const registerRouter = `${host}/api/auth/register`;
export const loginRouter = `${host}/api/auth/login`;
export const setAvatarRouter = `${host}/api/auth/avatar`;
export const allUsersRoute = `${host}/api/auth/all-users`;
export const userRoute = `${host}/api/auth/user`;
export const sendMessageRouter = `${host}/api/messages/add`;
export const getAllMessagesRoute = `${host}/api/messages`;
